CREATE TABLE BOOKING
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ID_GOOD BIGINT NOT NULL,
  ID_POINT1 BIGINT NOT NULL,
  ID_POINT2 BIGINT NOT NULL,
  ID_CUSTOMER INTEGER,
  STATUS VARCHAR(15)
);
CREATE TABLE CUSTOMER
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  EMAIL VARCHAR(255),
  PASSWORD VARCHAR(255) NOT NULL,
  FIRSTNAME VARCHAR(255),
  ROLE VARCHAR(15)
);
CREATE TABLE DISTANCE
(
  ID_POINT1 INTEGER NOT NULL,
  ID_POINT2 INTEGER NOT NULL,
  DISTANCE INTEGER NOT NULL,
  PRIMARY KEY (ID_POINT1, ID_POINT2)
);
CREATE TABLE GOODS
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  WEIGHT INTEGER NOT NULL,
  VOLUME INTEGER NOT NULL,
  COST INTEGER NOT NULL,
  COMMENT VARCHAR(255) NOT NULL
);
CREATE TABLE POINTS
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  POINT VARCHAR(50) NOT NULL
);
CREATE TABLE TRUCK
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  MODEL VARCHAR(50) NOT NULL,
  WEIGHT_CAPACITY INTEGER NOT NULL,
  VOLUME_CAPACITY INTEGER NOT NULL,
  PRICE_PER_KM INTEGER NOT NULL,
  STATUS VARCHAR(20) NOT NULL
);
ALTER TABLE BOOKING ADD FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER (ID);
ALTER TABLE BOOKING ADD FOREIGN KEY (ID_GOOD) REFERENCES GOODS (ID);
ALTER TABLE BOOKING ADD FOREIGN KEY (ID_POINT1) REFERENCES POINTS (ID);
ALTER TABLE BOOKING ADD FOREIGN KEY (ID_POINT2) REFERENCES POINTS (ID);
CREATE INDEX CONSTRAINT_2EA6_INDEX_D ON BOOKING (ID_CUSTOMER);
CREATE INDEX CONSTRAINT_2EA_INDEX_D ON BOOKING (ID_POINT2);
CREATE INDEX CONSTRAINT_2E_INDEX_D ON BOOKING (ID_POINT1);
CREATE INDEX CONSTRAINT_2_INDEX_D ON BOOKING (ID_GOOD);
ALTER TABLE DISTANCE ADD FOREIGN KEY (ID_POINT1) REFERENCES POINTS (ID);
ALTER TABLE DISTANCE ADD FOREIGN KEY (ID_POINT2) REFERENCES POINTS (ID);
