INSERT INTO PUBLIC.CUSTOMER (ID, EMAIL, PASSWORD, FIRSTNAME, ROLE) VALUES (1, 'zhasulan@mail.com', '123', 'Zhasulan', 'CUSTOMER');
INSERT INTO PUBLIC.CUSTOMER (ID, EMAIL, PASSWORD, FIRSTNAME, ROLE) VALUES (6, 'damir@mail.com', 'damir', 'Damir', 'CUSTOMER');
INSERT INTO PUBLIC.CUSTOMER (ID, EMAIL, PASSWORD, FIRSTNAME, ROLE) VALUES (7, 'admin@info.com', 'admin', 'admin', 'ADMIN');
