INSERT INTO PUBLIC.TRUCK (ID, MODEL, WEIGHT_CAPACITY, VOLUME_CAPACITY, PRICE_PER_KM, STATUS) VALUES (11, 'KamAz', 5000, 12, 60, 'EMPTY');
INSERT INTO PUBLIC.TRUCK (ID, MODEL, WEIGHT_CAPACITY, VOLUME_CAPACITY, PRICE_PER_KM, STATUS) VALUES (9, 'Scania', 8000, 56, 70, 'EMPTY');
INSERT INTO PUBLIC.TRUCK (ID, MODEL, WEIGHT_CAPACITY, VOLUME_CAPACITY, PRICE_PER_KM, STATUS) VALUES (10, 'Foton', 3000, 20, 50, 'EMPTY');
INSERT INTO PUBLIC.TRUCK (ID, MODEL, WEIGHT_CAPACITY, VOLUME_CAPACITY, PRICE_PER_KM, STATUS) VALUES (8, 'Газель', 1500, 9, 30, 'EMPTY');
INSERT INTO PUBLIC.TRUCK (ID, MODEL, WEIGHT_CAPACITY, VOLUME_CAPACITY, PRICE_PER_KM, STATUS) VALUES (12, 'Daf', 20000, 100, 100, 'EMPTY');
INSERT INTO PUBLIC.TRUCK (ID, MODEL, WEIGHT_CAPACITY, VOLUME_CAPACITY, PRICE_PER_KM, STATUS) VALUES (14, 'Volvo', 20000, 110, 102, 'EMPTY');
