INSERT INTO PUBLIC.POINTS (ID, POINT) VALUES (1, 'Астана');
INSERT INTO PUBLIC.POINTS (ID, POINT) VALUES (2, 'Алматы');
INSERT INTO PUBLIC.POINTS (ID, POINT) VALUES (3, 'Караганды');
INSERT INTO PUBLIC.POINTS (ID, POINT) VALUES (4, 'Тараз');
INSERT INTO PUBLIC.POINTS (ID, POINT) VALUES (5, 'Кокшетау');
